import type { Category, Product, PaymentMethod } from "@/features/topup/types";
import type { Transaction } from "@/features/transaction/types";

export const CATEGORIES: Category[] = [
  // Internet & Komunikasi
  {
    id: "cat-1",
    name: "Pulsa",
    slug: "pulsa",
    group: "Internet & Komunikasi",
    icon: "📱",
    description: "Isi pulsa semua operator",
    color: "from-green-500 to-emerald-600",
  },
  {
    id: "cat-2",
    name: "Paket Data",
    slug: "paket-data",
    group: "Internet & Komunikasi",
    icon: "📶",
    description: "Beli paket data internet semua operator",
    color: "from-blue-500 to-indigo-600",
  },
  {
    id: "cat-3",
    name: "Telepon Pascabayar",
    slug: "telco-postpaid",
    group: "Internet & Komunikasi",
    icon: "📞",
    description: "Bayar tagihan telepon pascabayar",
    color: "from-sky-500 to-blue-600",
  },
  {
    id: "cat-4",
    name: "Telkom / Telepon Rumah",
    slug: "telkom",
    group: "Internet & Komunikasi",
    icon: "🏠",
    description: "Bayar tagihan Telkom dan telepon rumah",
    color: "from-red-500 to-rose-600",
  },

  // Hiburan & Gaming
  {
    id: "cat-5",
    name: "Top Up Game",
    slug: "topup-game",
    group: "Hiburan & Gaming",
    icon: "🎮",
    description: "Top up diamond, UC, VP dan item game lainnya",
    color: "from-violet-500 to-purple-600",
  },
  {
    id: "cat-6",
    name: "TV Kabel / Streaming",
    slug: "tv-streaming",
    group: "Hiburan & Gaming",
    icon: "🎬",
    description: "Bayar TV kabel dan langganan streaming",
    color: "from-pink-500 to-rose-600",
  },

  // E-Wallet & Pembayaran Digital
  {
    id: "cat-7",
    name: "Top Up e-Wallet",
    slug: "e-wallet",
    group: "E-Wallet & Pembayaran Digital",
    icon: "💳",
    description: "Top up GoPay, DANA, OVO, LinkAja, dan lainnya",
    color: "from-purple-500 to-violet-600",
  },

  // Tagihan
  {
    id: "cat-8",
    name: "Token Listrik PLN",
    slug: "pln-token",
    group: "Tagihan",
    icon: "⚡",
    description: "Beli token listrik PLN prabayar",
    color: "from-amber-400 to-yellow-500",
  },
  {
    id: "cat-9",
    name: "Tagihan Listrik",
    slug: "pln-pascabayar",
    group: "Tagihan",
    icon: "💡",
    description: "Bayar tagihan listrik PLN pascabayar",
    color: "from-yellow-500 to-amber-600",
  },
  {
    id: "cat-10",
    name: "Tagihan Air (PDAM)",
    slug: "pdam",
    group: "Tagihan",
    icon: "💧",
    description: "Bayar tagihan air PDAM",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "cat-11",
    name: "Tagihan Internet (ISP)",
    slug: "isp",
    group: "Tagihan",
    icon: "🌐",
    description: "Bayar tagihan internet rumah",
    color: "from-teal-500 to-cyan-600",
  },
  {
    id: "cat-12",
    name: "PBB",
    slug: "pbb",
    group: "Tagihan",
    icon: "🏛️",
    description: "Bayar Pajak Bumi dan Bangunan",
    color: "from-orange-500 to-red-600",
  },
  {
    id: "cat-13",
    name: "Multifinance",
    slug: "multifinance",
    group: "Tagihan",
    icon: "🏍️",
    description: "Bayar cicilan kendaraan dan elektronik",
    color: "from-slate-500 to-zinc-600",
  },
  {
    id: "cat-14",
    name: "Gas",
    slug: "gas",
    group: "Tagihan",
    icon: "🔥",
    description: "Bayar tagihan gas PGN",
    color: "from-red-400 to-orange-500",
  },

  // Asuransi & Kesehatan
  {
    id: "cat-15",
    name: "BPJS Kesehatan",
    slug: "bpjs-kesehatan",
    group: "Asuransi & Kesehatan",
    icon: "🏥",
    description: "Bayar iuran BPJS Kesehatan",
    color: "from-emerald-500 to-green-600",
  },
  {
    id: "cat-16",
    name: "BPJS Ketenagakerjaan",
    slug: "bpjs-ketenagakerjaan",
    group: "Asuransi & Kesehatan",
    icon: "👷",
    description: "Bayar iuran BPJS Ketenagakerjaan",
    color: "from-blue-500 to-sky-600",
  },
  {
    id: "cat-17",
    name: "Asuransi Digital",
    slug: "asuransi-digital",
    group: "Asuransi & Kesehatan",
    icon: "🛡️",
    description: "Beli dan bayar asuransi digital",
    color: "from-indigo-500 to-violet-600",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Mobile Legends: Bang Bang",
    slug: "mobile-legends",
    categoryId: "cat-5",
    categorySlug: "topup-game",
    image: "/images/ml.png",
    publisher: "Moonton",
    description:
      "Top up Diamond Mobile Legends Bang Bang dengan harga termurah dan proses instan.",
    inputFields: [
      {
        key: "userId",
        label: "User ID",
        placeholder: "Masukkan User ID",
        type: "number",
        required: true,
      },
      {
        key: "zoneId",
        label: "Zone ID",
        placeholder: "Masukkan Zone ID",
        type: "number",
        required: true,
      },
    ],
    nominals: [
      { id: "nom-1", name: "3 Diamonds", amount: 3, price: 1500 },
      { id: "nom-2", name: "5 Diamonds", amount: 5, price: 2500 },
      { id: "nom-3", name: "12 Diamonds", amount: 12, price: 3500 },
      { id: "nom-4", name: "19 Diamonds", amount: 19, price: 5500 },
      { id: "nom-5", name: "28 Diamonds", amount: 28, price: 7500 },
      { id: "nom-6", name: "44 Diamonds", amount: 44, price: 10000 },
      {
        id: "nom-7",
        name: "59 Diamonds",
        amount: 59,
        price: 14000,
        originalPrice: 15000,
        isPromo: true,
      },
      { id: "nom-8", name: "85 Diamonds", amount: 85, price: 19000 },
      {
        id: "nom-9",
        name: "170 Diamonds",
        amount: 170,
        price: 37000,
        originalPrice: 40000,
        isPromo: true,
      },
      { id: "nom-10", name: "240 Diamonds", amount: 240, price: 52000 },
      { id: "nom-11", name: "344 Diamonds", amount: 344, price: 73000 },
      {
        id: "nom-12",
        name: "514 Diamonds",
        amount: 514,
        price: 108000,
        originalPrice: 115000,
        isPromo: true,
      },
      { id: "nom-13", name: "706 Diamonds", amount: 706, price: 148000 },
      { id: "nom-14", name: "2010 Diamonds", amount: 2010, price: 420000 },
    ],
  },
  {
    id: "prod-2",
    name: "Free Fire",
    slug: "free-fire",
    categoryId: "cat-5",
    categorySlug: "topup-game",
    image: "/images/ff.png",
    publisher: "Garena",
    description:
      "Top up Diamond Free Fire instant dan murah. Proses otomatis 24 jam.",
    inputFields: [
      {
        key: "userId",
        label: "Player ID",
        placeholder: "Masukkan Player ID",
        type: "number",
        required: true,
      },
    ],
    nominals: [
      { id: "ff-1", name: "5 Diamonds", amount: 5, price: 1000 },
      { id: "ff-2", name: "12 Diamonds", amount: 12, price: 2000 },
      { id: "ff-3", name: "50 Diamonds", amount: 50, price: 7000 },
      {
        id: "ff-4",
        name: "70 Diamonds",
        amount: 70,
        price: 9500,
        originalPrice: 10000,
        isPromo: true,
      },
      { id: "ff-5", name: "140 Diamonds", amount: 140, price: 19000 },
      { id: "ff-6", name: "355 Diamonds", amount: 355, price: 47000 },
      {
        id: "ff-7",
        name: "720 Diamonds",
        amount: 720,
        price: 95000,
        originalPrice: 100000,
        isPromo: true,
      },
      { id: "ff-8", name: "1450 Diamonds", amount: 1450, price: 190000 },
    ],
  },
  {
    id: "prod-3",
    name: "Genshin Impact",
    slug: "genshin-impact",
    categoryId: "cat-5",
    categorySlug: "topup-game",
    image: "/images/gi.png",
    publisher: "miHoYo",
    description:
      "Top up Genesis Crystal Genshin Impact. Support semua server.",
    inputFields: [
      {
        key: "uid",
        label: "UID",
        placeholder: "Masukkan UID Genshin",
        type: "number",
        required: true,
      },
      {
        key: "server",
        label: "Server",
        placeholder: "Pilih server",
        type: "select",
        required: true,
        options: [
          { label: "Asia", value: "asia" },
          { label: "America", value: "america" },
          { label: "Europe", value: "europe" },
          { label: "TW/HK/MO", value: "tw-hk-mo" },
        ],
      },
    ],
    nominals: [
      { id: "gi-1", name: "60 Genesis Crystals", amount: 60, price: 16000 },
      { id: "gi-2", name: "300 Genesis Crystals", amount: 300, price: 79000 },
      {
        id: "gi-3",
        name: "980 Genesis Crystals",
        amount: 980,
        price: 249000,
        originalPrice: 260000,
        isPromo: true,
      },
      {
        id: "gi-4",
        name: "1980 Genesis Crystals",
        amount: 1980,
        price: 479000,
      },
      {
        id: "gi-5",
        name: "3280 Genesis Crystals",
        amount: 3280,
        price: 799000,
      },
      {
        id: "gi-6",
        name: "6480 Genesis Crystals",
        amount: 6480,
        price: 1599000,
      },
    ],
  },
  {
    id: "prod-4",
    name: "PUBG Mobile",
    slug: "pubg-mobile",
    categoryId: "cat-5",
    categorySlug: "topup-game",
    image: "/images/pubg.png",
    publisher: "Tencent",
    description: "Top up UC PUBG Mobile murah dan cepat.",
    inputFields: [
      {
        key: "playerId",
        label: "Player ID",
        placeholder: "Masukkan Player ID",
        type: "number",
        required: true,
      },
    ],
    nominals: [
      { id: "pubg-1", name: "60 UC", amount: 60, price: 15000 },
      { id: "pubg-2", name: "325 UC", amount: 325, price: 75000 },
      {
        id: "pubg-3",
        name: "660 UC",
        amount: 660,
        price: 149000,
        originalPrice: 160000,
        isPromo: true,
      },
      { id: "pubg-4", name: "1800 UC", amount: 1800, price: 375000 },
      { id: "pubg-5", name: "3850 UC", amount: 3850, price: 749000 },
    ],
  },
  {
    id: "prod-5",
    name: "Valorant",
    slug: "valorant",
    categoryId: "cat-5",
    categorySlug: "topup-game",
    image: "/images/val.png",
    publisher: "Riot Games",
    description: "Top up Valorant Points dengan harga terbaik.",
    inputFields: [
      {
        key: "riotId",
        label: "Riot ID",
        placeholder: "Contoh: Player#TAG",
        type: "text",
        required: true,
      },
    ],
    nominals: [
      { id: "val-1", name: "125 VP", amount: 125, price: 15000 },
      { id: "val-2", name: "420 VP", amount: 420, price: 50000 },
      {
        id: "val-3",
        name: "700 VP",
        amount: 700,
        price: 80000,
        originalPrice: 85000,
        isPromo: true,
      },
      { id: "val-4", name: "1375 VP", amount: 1375, price: 150000 },
      { id: "val-5", name: "2400 VP", amount: 2400, price: 250000 },
      { id: "val-6", name: "4000 VP", amount: 4000, price: 400000 },
      { id: "val-7", name: "8150 VP", amount: 8150, price: 800000 },
    ],
  },
  {
    id: "prod-6",
    name: "Telkomsel",
    slug: "telkomsel",
    categoryId: "cat-1",
    categorySlug: "pulsa",
    image: "/images/telkomsel.png",
    publisher: "Telkomsel",
    description: "Isi pulsa Telkomsel cepat dan mudah.",
    inputFields: [
      {
        key: "phone",
        label: "Nomor HP",
        placeholder: "Contoh: 08123456789",
        type: "text",
        required: true,
      },
    ],
    nominals: [
      { id: "tsel-1", name: "Pulsa 5.000", amount: 5000, price: 6500 },
      { id: "tsel-2", name: "Pulsa 10.000", amount: 10000, price: 11500 },
      { id: "tsel-3", name: "Pulsa 15.000", amount: 15000, price: 16200 },
      { id: "tsel-4", name: "Pulsa 20.000", amount: 20000, price: 21000 },
      { id: "tsel-5", name: "Pulsa 25.000", amount: 25000, price: 26000 },
      { id: "tsel-6", name: "Pulsa 50.000", amount: 50000, price: 50500 },
      { id: "tsel-7", name: "Pulsa 100.000", amount: 100000, price: 100000 },
    ],
  },
];

export const PAYMENT_METHODS: PaymentMethod[] = [
  {
    id: "pay-1",
    name: "QRIS",
    group: "QRIS",
    icon: "📱",
    fee: 0,
    feeType: "fixed",
  },
  {
    id: "pay-2",
    name: "GoPay",
    group: "E-Wallet",
    icon: "💚",
    fee: 1000,
    feeType: "fixed",
  },
  {
    id: "pay-3",
    name: "OVO",
    group: "E-Wallet",
    icon: "💜",
    fee: 1000,
    feeType: "fixed",
  },
  {
    id: "pay-4",
    name: "DANA",
    group: "E-Wallet",
    icon: "💙",
    fee: 1000,
    feeType: "fixed",
  },
  {
    id: "pay-5",
    name: "ShopeePay",
    group: "E-Wallet",
    icon: "🧡",
    fee: 1000,
    feeType: "fixed",
  },
  {
    id: "pay-6",
    name: "BCA Virtual Account",
    group: "Bank Transfer",
    icon: "🏦",
    fee: 2500,
    feeType: "fixed",
  },
  {
    id: "pay-7",
    name: "BNI Virtual Account",
    group: "Bank Transfer",
    icon: "🏦",
    fee: 2500,
    feeType: "fixed",
  },
  {
    id: "pay-8",
    name: "BRI Virtual Account",
    group: "Bank Transfer",
    icon: "🏦",
    fee: 2500,
    feeType: "fixed",
  },
  {
    id: "pay-9",
    name: "Mandiri Virtual Account",
    group: "Bank Transfer",
    icon: "🏦",
    fee: 2500,
    feeType: "fixed",
  },
  {
    id: "pay-10",
    name: "Indomaret",
    group: "Convenience Store",
    icon: "🏪",
    fee: 2500,
    feeType: "fixed",
  },
  {
    id: "pay-11",
    name: "Alfamart",
    group: "Convenience Store",
    icon: "🏪",
    fee: 2500,
    feeType: "fixed",
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: "trx-1",
    orderId: "RZZ-A1B2C3-X9Y8Z7",
    productName: "Mobile Legends: Bang Bang",
    productImage: "/images/ml.png",
    nominal: "170 Diamonds",
    amount: 37000,
    fee: 0,
    totalAmount: 37000,
    paymentMethod: "QRIS",
    status: "success",
    userInputs: { userId: "123456789", zoneId: "5432" },
    createdAt: "2026-04-25T10:30:00Z",
    updatedAt: "2026-04-25T10:31:00Z",
  },
  {
    id: "trx-2",
    orderId: "RZZ-D4E5F6-W6V5U4",
    productName: "Free Fire",
    productImage: "/images/ff.png",
    nominal: "355 Diamonds",
    amount: 47000,
    fee: 1000,
    totalAmount: 48000,
    paymentMethod: "GoPay",
    status: "processing",
    userInputs: { userId: "987654321" },
    createdAt: "2026-04-25T14:20:00Z",
    updatedAt: "2026-04-25T14:20:00Z",
  },
  {
    id: "trx-3",
    orderId: "RZZ-G7H8I9-T3S2R1",
    productName: "Genshin Impact",
    productImage: "/images/gi.png",
    nominal: "300 Genesis Crystals",
    amount: 79000,
    fee: 2500,
    totalAmount: 81500,
    paymentMethod: "BCA Virtual Account",
    status: "pending",
    userInputs: { uid: "800123456", server: "Asia" },
    createdAt: "2026-04-26T08:00:00Z",
    updatedAt: "2026-04-26T08:00:00Z",
  },
];
